development:
  adapter: postgresql
  encoding: unicode
  database: flick1_development
  pool: 5
  username: admin
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: flick1_test
  pool: 5
  username: admin
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: flick1_production
  pool: 5
  username: admin
  password:
  host: localhost
